## Getting familiar with numpy arrays

#### 1) Import the numpy module and use a shorter namespace

In [1]:
import numpy as np

#### 2) Create an array containing only 0s with shape (5,5)

In [10]:
array=np.zeros((2,6))
print(array[0])

[0. 0. 0. 0. 0. 0.]


#### 3) Get the shape of this array

In [35]:
array.shape

(5, 3)


#### 4) Fill the array with random values, uniformly distributed between -1 and 1, using a loop

In [38]:
nb_lines = array.shape[0]
nb_columns = array.shape[1]
for line in range(nb_lines):
    for column in range(nb_columns):
        array[line, column] = np.random.uniform(-1, 1)

In [16]:
array

array([[-0.14248188,  0.32880571, -0.21406896, -0.48408913, -0.11196526,
         0.04325461],
       [-0.20552454, -0.25345274,  0.55798291, -0.47889379,  0.66911186,
         0.73633456]])

#### 5) Rebuild an (5,5) random array with unifomly distributed values without using a loop

In [29]:
array = np.random.uniform(-1, 1, (5, 3))

In [30]:
array

array([[ 0.01518063,  0.09636176, -0.45441924],
       [-0.52732153,  0.67226406, -0.43013392],
       [ 0.10326755,  0.22273577, -0.04782905],
       [ 0.00251406,  0.76106696, -0.82786023],
       [ 0.15788658, -0.61714468, -0.91596989]])

#### 6) Transpose the array

In [31]:
array.T

array([[ 0.01518063, -0.52732153,  0.10326755,  0.00251406,  0.15788658],
       [ 0.09636176,  0.67226406,  0.22273577,  0.76106696, -0.61714468],
       [-0.45441924, -0.43013392, -0.04782905, -0.82786023, -0.91596989]])

#### 7) Check the sign of entries of th array

In [32]:
array >= 0

array([[ True,  True, False],
       [False,  True, False],
       [ True,  True, False],
       [ True,  True, False],
       [ True, False, False]])

#### 8) Get the indexes where the array is positive

In [33]:
np.where(array >= 0)

(array([0, 0, 1, 2, 2, 3, 3, 4]), array([0, 1, 1, 0, 1, 0, 1, 0]))

In [45]:
array

array([[ 0.57094843,  0.12937255, -0.67920725],
       [ 0.89492646, -0.47048495,  0.48283882],
       [-0.88812305,  0.89135566,  0.11703082],
       [ 0.22566329, -0.14278495, -0.25792282],
       [-0.51674701, -0.46320574, -0.76161228]])

#### 9) Compute the sum of the element in the second line with a loop

In [39]:
result = 0
for column in range(nb_columns):
    result += array[1, column]

In [40]:
result

0.9072803298241086

#### 10) Compute the sum of the elements in the second line without a loop

In [43]:
array[1].sum()

0.9072803298241086

#### 11) Compute the sum of the elements in all lines the keword argument "axis" 

In [46]:
array.sum(axis=1)

array([ 0.02111373,  0.90728033,  0.12026343, -0.17504447, -1.74156502])

#### 12) Verify that the results are equal

#### 13) Compute the sum of all elements in the array

In [47]:
array.sum()

-0.8679519991431144

#### 14) Check if all entries are positive

In [48]:
np.all(array >=0)

False

In [51]:
array2 = np.random.randint(-10, 10, (5, 3))
array3 = np.random.randint(-10, 10, (2, 5))

In [52]:
array3

array([[-7,  4, -1,  6, -1],
       [-8,  0,  4,  5, -4]])

In [50]:
array2

array([[ 6, -9,  8],
       [-6,  5,  9],
       [-9,  9,  4],
       [ 5,  0,  5],
       [-4,  9, -1]])

In [57]:
np.matmul(array3, array2)

array([[-13, -35,  27],
       [-62,   8,  34]])

In [58]:
array3 @ array2

array([[-13, -35,  27],
       [-62,   8,  34]])