## Getting familiar with numpy arrays

#### 1) Import the numpy module and use a shorter namespace

In [14]:
import numpy as np

#### 2) Create an array containing only 0s with shape (5,5)

In [15]:
array=np.zeros(shape=(5,6))
print(array)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


#### 3) Get the shape of this array

In [7]:
array.shape

(5, 6)


#### 4) Fill the array with random values, uniformly distributed between -1 and 1, using a loop

In [16]:
nb_lines = array.shape[0]
nb_columns = array.shape[1]
for line in range(nb_lines):
    for column in range(nb_columns):
        array[line, column] = np.random.uniform(low=-1, high=1)

In [9]:
array

array([[ 0.49523223, -0.71249361,  0.52761453, -0.02458164, -0.6050144 ,
         0.21245823],
       [ 0.20098796, -0.72476481,  0.26015914, -0.71963101, -0.25478822,
        -0.28887537],
       [ 0.33115728,  0.548807  , -0.50858176,  0.75573336,  0.846451  ,
         0.37341823],
       [ 0.03794003,  0.3816921 ,  0.26547093, -0.4152154 , -0.84513274,
        -0.15271488],
       [-0.77615792,  0.94742303,  0.09480717, -0.76559374,  0.94065313,
        -0.72152991]])

#### 5) Rebuild an (5,5) random array with unifomly distributed values without using a loop

In [42]:
array_1 = np.random.randint(low=-1, high=2, size=(3, 3))
array_2 = np.random.randint(low=-1, high=1, size=(3, 3))
array_3 = np.random.randint(low=-1, high=1, size=(3, 5))

In [38]:
array_1

array([[-1,  1,  0],
       [ 0, -1, -1],
       [ 0,  1, -1]])

In [39]:
array_2

array([[ 0, -1, -1],
       [ 0, -1,  0],
       [-1,  0, -1]])

In [43]:
array_1 @ array_3

array([[-2, -1,  0,  0, -2],
       [ 1,  0,  1,  0,  1],
       [ 2,  0,  1,  0,  2]])

In [41]:
array_1 * array_2

array([[ 0, -1,  0],
       [ 0,  1,  0],
       [ 0,  0,  1]])

#### 6) Transpose the array

In [24]:
array.T

array([[-0.11986344,  0.60055998,  0.97037934,  0.13158584,  0.64565283],
       [ 0.09541796,  0.02202205, -0.22101911,  0.98416514, -0.23426752],
       [ 0.76710169, -0.91689577,  0.05990974,  0.95424806, -0.56933952]])

#### 7) Check the sign of entries of th array

In [44]:
array >= 0

array([[False, False,  True, False,  True],
       [ True, False,  True,  True, False],
       [ True, False,  True,  True,  True]])

#### 8) Get the indexes where the array is positive

In [45]:
np.where(array >= 0)

(array([0, 0, 1, 1, 1, 2, 2, 2, 2]), array([2, 4, 0, 2, 3, 0, 2, 3, 4]))

In [45]:
array

array([[ 0.57094843,  0.12937255, -0.67920725],
       [ 0.89492646, -0.47048495,  0.48283882],
       [-0.88812305,  0.89135566,  0.11703082],
       [ 0.22566329, -0.14278495, -0.25792282],
       [-0.51674701, -0.46320574, -0.76161228]])

#### 9) Compute the sum of the element in the second line with a loop

In [39]:
result = 0
for column in range(nb_columns):
    result += array[1, column]

In [40]:
result

0.9072803298241086

#### 10) Compute the sum of the elements in the second line without a loop

In [51]:
array_3

array([[-1,  0, -1,  0, -1],
       [-1, -1,  0,  0, -1],
       [-1,  0,  0,  0, -1]])

In [52]:
array_3[1].sum()

-3

#### 11) Compute the sum of the elements in all lines the keword argument "axis" 

In [55]:
array_3.sum(axis=0)

array([-3, -1, -1,  0, -3])

#### 12) Verify that the results are equal

#### 13) Compute the sum of all elements in the array

In [47]:
array.sum()

-0.8679519991431144

#### 14) Check if all entries are positive

In [56]:
np.all(array >=0)

False

In [51]:
array2 = np.random.randint(-10, 10, (5, 3))
array3 = np.random.randint(-10, 10, (2, 5))

In [52]:
array3

array([[-7,  4, -1,  6, -1],
       [-8,  0,  4,  5, -4]])

In [50]:
array2

array([[ 6, -9,  8],
       [-6,  5,  9],
       [-9,  9,  4],
       [ 5,  0,  5],
       [-4,  9, -1]])

In [57]:
np.matmul(array3, array2)

array([[-13, -35,  27],
       [-62,   8,  34]])

In [58]:
array3 @ array2

array([[-13, -35,  27],
       [-62,   8,  34]])